version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.feather

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_rates_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2018-01-01 to 2018-08-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inpu*.feather
  
  generate_rates_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2018-09-01 to 2019-03-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inp*.feather

  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py
    needs:
      [
        generate_rates_1,
        generate_rates_2,
        generate_ethnicity,
      ]
    outputs:
      highly_sensitive:
        cohort: output/measures/in*.feather
  
  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_rates --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_rates_1,
        generate_rates_2,
        join_ethnicity,
      ]
    outputs:
      moderately_sensitive:
        measure_csv1: output/measures/measure_prevalence*_rate.csv
        measure_csv2: output/measures/measure_prevalencebyRegion*_rate.csv
        measure_csv3: output/measures/measure_prevalencebyIMD*_rate.csv
        measure_csv4: output/measures/measure_prevalencebyEthnicity*_rate.csv
        measure_csv5: output/measures/measure_prevalencebyAge*_rate.csv
        measure_csv6: output/measures/measure_incidence*_rate.csv
        measure_csv7: output/measures/measure_incidencebyRegion*_rate.csv
        measure_csv8: output/measures/measure_incidencebyIMD*_rate.csv
        measure_csv9: output/measures/measure_incidenceyEthnicity*_rate.csv
        measure_csv10: output/measures/measure_incidencebyAge*_rate.csv

  # describe_trends:
  #   run: r:latest analysis/Descriptive_trends.R
  #   needs: 
  #     [
  #       generate_measures,
  #     ]
  #   outputs:
  #     moderately_sensitive:
  #       Fig1: output/ADTinj_count1.png
  #       Fig2: output/ADTinj_rates1.png
  #       Fig3: output/ADTinjbyRegion1.png
  #       Fig4: output/ADTinjbyIMD1.png
  #       Fig5: output/ADTinjbyEthnicity1.png
  #       Fig6: output/ADTinjbyAge1.png
  #       Fig7: output/ADToral_count1.png
  #       Fig8: output/ADToral_rates1.png
  #       Fig9: output/ADToralbyRegion1.png
  #       Fig10: output/ADToralbyIMD1.png
  #       Fig11: output/ADToralbyEthnicity1.png
  #       Fig12: output/ADToralbyAge1.png